### ISSUE TITLE
Buttons in plot window crashes RStudio 

### ISSUE THREAD

**Issue by DaveEvenden** [talgalili/heatmaply#17]
Run the mtcars example...
heatmaply(mtcars, k_col = 2, k_row = 3) %>% layout(margin = list(l = 130, b = 40))

hit 'Autoscale' or 'Zoom out' 

'RStudio has stopped working' message

**Comment by talgalili** [comment]
Thanks for the report @DaveEvenden 
This is a bug in plotly. Since the plotly R package is currently under a lot of development/improvement - I hope this will get resolved in the next couple of weeks.
I will keep this ticket open until I will see it resolved.

With regards,
Tal

**Comment by DaveEvenden** [comment]
Thanks Tal,
I raised it as my introduction to this package was via this website... ...
http://www.r-bloggers.com/heatmaply-interactive-heat-maps/ 
Where it is stated that .... 'You will get this output in your browser (or **RStudio console**):' (my bold)
And as I am an RStudio fanboy....... :-)

**Comment by talgalili** [comment]
I use and love Rstudio as well :)
In the meantime, the zoom out feature works when clicking the home button (but not when double clicking the heatmap).
This is indeed a feature that "should" work, it is a bug in plotly (that I believe was already reported - so it should be fixed).

Cheers :)
Tal

**Comment by Alanocallaghan** [comment]
Does this still happen?

**Comment by DaveEvenden** [comment]
Yes - I still get the same bug (IIRC - it was 3 years ago) but only in the RStudio's plot pane.
Opening the plot in a separate window using 'Viewer Zoom', the controls seem to work okay.

**Comment by Alanocallaghan** [comment]
Ah sorry to hear. It sounds like a plotly bug rather than heatmaply so I'm closing this
