### ISSUE TITLE
hide_colobar and hide colored icons 

### ISSUE THREAD

**Issue by seanlally** [talgalili/heatmaply#171]
I had a quick question about your heatmaply library. There is a
scenario where we wish to have no legend/colorbar show at all but when
we use hide_colorbar option, it produces colorful dots over the numbers
displayed in each cell. Is there a way to remove the colorbar and the
dots that appear? Reading through the documentation of the heatmaply
library, nothing jumped out at us as a solution.

**Comment by Shmeallum** [comment]
Something like `  p1 <- heatmaply(singletrimpct,colors = colors, limits = c(0, 100), dendrogram = "none", grid_gap = 1, draw_cellnote = TRUE,
                  cellnote_textposition = "middle center", srtCol = 0, main = "Dashboard Summary", hide_colorbar = TRUE)`

produces an output that looks like this 

![heatmap_symbols](https://user-images.githubusercontent.com/6708671/38737784-e9f371a6-3ef5-11e8-9800-c3ebf2278aac.png)

if `hide_colorbar = FALSE`, the dots over the numbers go away, but obviously the colorbar comes back.

I can work on putting a script together to do show this, but i have only ever worked with shiny so i don't know exactly what is needed for a standalone script to make this run for you.

**Comment by Alanocallaghan** [comment]
I can't reproduce that figure - it actually errors when I try to include cellnote at all, which is much worse.

Could you post `sessionInfo()`? I'll try to solve. Thanks.

**Comment by seanlally** [comment]
`  p1 <- heatmaply(singletrimpct,colors = colorRampPalette(c("#ff2015", "#ff6961", "#FDFD55", "#3ace3a"))(100), limits = c(0, 100), dendrogram = "none", grid_gap = 1, draw_cellnote = TRUE,
                  cellnote_textposition = "middle center", srtCol = 0, main = "Dashboard Summary", hide_colorbar = TRUE)`  does this work any better? colors was another variable for us that i forgot to translate so you could use it. singletrimpct is just a single column data.frame we assing rownames and a colname to.

**Comment by seanlally** [comment]
```R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4          tidyr_0.8.0          shinydashboard_0.7.0 shinyjs_1.0          shiny_1.0.5         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     bindr_0.1        magrittr_1.5     xtable_1.8-2     R6_2.2.2         rlang_0.1.6      httr_1.3.1       tools_3.4.3     
 [9] htmltools_0.3.6  yaml_2.1.16      digest_0.6.13    assertthat_0.2.0 tibble_1.4.1     bindrcpp_0.2     purrr_0.2.4      glue_1.2.0      
[17] mime_0.5         compiler_3.4.3   pillar_1.0.1     jsonlite_1.5     httpuv_1.3.5     pkgconfig_2.0.1 ```
is the sessionInfo() on my local rstudio, but we only actually run this code on our shiny server. i will see if i can get the sessionInfo() from that.

**Comment by seanlally** [comment]
```R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3
``` sessionInfo from our server when in an R shell. 
I dont know how to get it specifcally for the shiny app running.

**Comment by Alanocallaghan** [comment]
That should be fine, thanks

**Comment by Alanocallaghan** [comment]
Hi @seanlally - if you try this branch https://github.com/talgalili/heatmaply/pull/172, I've pushed a fix. Not sure if it's permanent as I'm not sure why the issue is arising, so I won't merge to master yet (eg, `devtools::install_github("talgalili/heatmaply", ref="marker_cellnote")`

**Comment by seanlally** [comment]
Will try out first thing Monday. Thank you.

**Comment by Alanocallaghan** [comment]
Cheers. I suspect it's an issue with plotly (maybe the R library) but that branch is a quick fix.

**Comment by seanlally** [comment]
@Alanocallaghan We are trying to use your fix, but the icons still show up. We don't know if its an issue with the fix or, more likely, an issue with use having to switch to using packrat at the same time as using this fix. We did the `devtools::install_github("talgalili/heatmaply", ref="marker_cellnote")` and packrat appears to be using the correct package. The hard part to tell is whether its picking up the correct branch (do not know why it would not).

**Comment by Alanocallaghan** [comment]
Not sure, I've never used packrat. I'll try to have another look tomorrow, and see if I can narrow down the issue a bit further.

**Comment by Alanocallaghan** [comment]
I still can't reproduce this using the branch, sorry Sean! Do you see any messages when producing the heatmap?

**Comment by talgalili** [comment]
This bug seems not updated (not reproducible?!).
Can we close this issue?
