### ISSUE TITLE
Unexpected error from col_side_colors 

### ISSUE THREAD

**Issue by gtollefson** [talgalili/heatmaply#194]
When trying to load a DataFrame of dimensions (9,191) as a col_side_colors input for a heatmap of dimensions (1164,191) I get the following pasted error and the code fails.

REvalError: Error: nrow(col_side_colors) not equal to ncol(x)

For a col_side_color bar that's positioned on top of the heatmap, shouldn't the number of columns of col_side_colors need to be equal to ncol(x)? Why does it evaluate whether the number of columns in the col_side_color match the number of rows in x, rather than the number of columns of x?

When I transpose the dataframe for col_side_colors to (191,9) the resulting col_side_colors does plot on top of the heatmap, but is predictably of the wrong dimension. I've attached a screenshot of the result. 

<img width="1095" alt="screen shot 2018-12-11 at 5 13 30 pm" src="https://user-images.githubusercontent.com/32968172/49833634-212fb180-fd68-11e8-817a-e4600d240e25.png">

Is this a bug?

I should note I am running this from Julia's RCall package on the REPL using reval("heatmaply()").

**Comment by Alanocallaghan** [comment]
Can you provide some example code please?

**Comment by gtollefson** [comment]
Yes! Sorry for not preemptively doing so. I've attached three files in the .zip file, one is loaded as input data loaded as dataframe for heatmaply plot function and the other is data loaded as dataframe for col_side_colors. A third is my repl output when running the reprex on my system. I am running Julia 0.6.3 and R 3.4.3.

You should be able to open the REPL and copy/paste the contents of the reprex_for_Alanocallaghan.jl file to see the error at the end. There is an additional error message that I failed to mention that only appears after running the code the first time. Every subsequent try the original error message is the only one printed. The error message that appears just before the error I've posted about is:

> ERROR: REvalError: Warning in doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found
Error: nrow(col_side_colors) not equal to ncol(x)

I've also attached a text file that includes the entire REPL output when I copy/paste the contents of reprex_for_Alanocallaghan.jl in case that is useful.

[files_for_reprex.zip](https://github.com/talgalili/heatmaply/files/2673843/files_for_reprex.zip)

**Comment by Alanocallaghan** [comment]
>For a col_side_color bar that's positioned on top of the heatmap, shouldn't the number of columns of col_side_colors need to be equal to ncol(x)? Why does it evaluate whether the number of columns in the col_side_color match the number of rows in x, rather than the number of columns of x?

That was how the interface was originally designed, but it's ultimately flawed because of how R stores tabular data; ie, data.frames are a list of vectors, with each entry being potentially of different type. If the data were stored as it is displayed, it would have to be stored as a matrix, or the columns of the input data.frame would really correspond to rows. I suppose this corresponds to the concept of "tidy data" as Hadley Wickham likes to advocate for.

When I run the following, I don't run into any issues. Are your package versions up to date? Also you should probably not translate the column side colour matrix to string colours, since heatmaply will do that internally anyway. If you want to represent 

```r
library(heatmaply)

pheno_data=read.table("pheno_data2.txt", header=TRUE, stringsAsFactors=FALSE)
pheno_data=t(pheno_data)
colorarray=matrix(0, dim(pheno_data)[1], dim(pheno_data)[2])

for (i in c(1:nrow(pheno_data))){
  colorarray[i,]=pheno_data[i,]
  colorarray[i,which(colorarray[i,]=="0")]="steelblue2"
  colorarray[i,which(colorarray[i,]=="1")]="mediumpurple2"
}

col_side_colors_1=(colorarray)
gt_num_array_1 <- read.csv("example_input_matrix.csv")           
heatmaply(gt_num_array_1, col_side_colors = t(col_side_colors_1))
```

By the way, you probably don't want to pass literal colour values into col_side_colors. Passing in meaningful string values and letting heatmaply handle the colour mapping makes a lot more sense.
EG:
```r
library(heatmaply)

pheno_data=read.table("pheno_data2.txt", header=TRUE, stringsAsFactors=FALSE)
pheno_data=t(pheno_data)
colorarray=matrix(0, dim(pheno_data)[1], dim(pheno_data)[2])

for (i in c(1:nrow(pheno_data))){
  colorarray[i,]=pheno_data[i,]
  colorarray[i,which(colorarray[i,]=="0")]="No"
  colorarray[i,which(colorarray[i,]=="1")]="Yes"
}

col_side_colors_1=(colorarray)
gt_num_array_1 <- read.csv("example_input_matrix.csv")           
heatmaply(gt_num_array_1, col_side_colors = t(col_side_colors_1), col_side_palette = c(Yes = "mediumpurple2", No="steelblue2"))
```

**Comment by gtollefson** [comment]
@Alanocallaghan 

Great! It works! How come you transposed the pheno_data twice rather than not at all? This seems to be the difference between our code.

**Comment by Alanocallaghan** [comment]
I didn't read the code thoroughly since the transpose worked immediately. Generating colorarray is largely superfluous; the following works fine:

```r
library(heatmaply)

pheno_data=read.table("pheno_data2.txt", header=TRUE, stringsAsFactors=FALSE)
gt_num_array_1 <- read.csv("example_input_matrix.csv")           
heatmaply(gt_num_array_1, col_side_colors = pheno_data, col_side_palette = c("1" = "mediumpurple2", "0"="steelblue2"))

```

**Comment by gtollefson** [comment]
@Alanocallaghan I've identified a particular attribute that is causing col_side_bar to mis-plot. When I define `label_names = c("Position", "Sample ID", "Genotype Value")` in heatmaply() I reproduce the error I described in my first post. Can you run the following code and see if you get the same result? I think there is some kind of interference between setting custom hover text and plotting 
col_side_color bars. 


```
library(heatmaply)

pheno_data=read.table("pheno_data2.txt", header=TRUE, stringsAsFactors=FALSE)
gt_num_array_1 <- read.csv("example_input_matrix.csv")           
heatmaply(gt_num_array_1, col_side_colors = pheno_data, col_side_palette = c("1" = "mediumpurple2", "0"="steelblue2"),label_names = c("Position", "Sample ID", "Genotype Value"))
```

**Comment by gtollefson** [comment]
Despite the warning message that hover labels will not work on the col_side_color bars, I do see hover labels. I wonder if the plotly code this depends upon is under development and buggy. 

I do not need to have hover labels in the col_side_color bars but don't think there's a way to turn them off for the color bars only. I would like them to remain defined for the heatmap.

The warning is:
WARNING: RCall.jl: Warning in heatmaply.heatmapr(hm, colors = colors, limits = limits, scale_fill_gradient_fun = scale_fill_gradient_fun,  :
  The hover text for col_side_colors is currently not implemented (due to an issue in plotly). We hope this would get resolved in future releases.

**Comment by Alanocallaghan** [comment]
The warning was related to an issue we had with plotly not showing hovertext for column side colours. It seems to be resolved, not sure when that happened. If you install the latest version from master the issue you described should be fixed

**Comment by gtollefson** [comment]
@Alanocallaghan No, the issue is not fixed and I think it should not have been closed.

I've installed the latest version of heatmaply and rerun the code. The col_side_bar still mis-plots. I think that the code for the col_side_bar is somehow creating a bug with the changes made to the plotly code.

Have you tried running the code I suggested running above? If you try I think you will see the issue and will recognize it as a bug in either the plotly dependency code or in heatmaply.

**Comment by Alanocallaghan** [comment]
Yes, I ran the code before and after applying the fix. Did you install the latest version from GitHub?

On 14 Dec 2018 7:38 pm, gtollefson <notifications@github.com> wrote:

@Alanocallaghan<https://github.com/Alanocallaghan> No, the issue is not fixed and I think it should not have been closed.

I've installed the latest version of heatmaply and rerun the code. The col_side_bar still mis-plots. I think that the code for the col_side_bar is somehow creating a bug with the changes made to the plotly code.

Have you tried running the code I suggested running above? If you try I think you will see the issue and will recognize it as a bug in either the plotly dependency code or in heatmaply.

**Comment by gtollefson** [comment]
@Alanocallaghan I had installed the stable release, not the most recent. Sorry for my confusion. I've installed using the instructions for installing the most recent version in master and updated plotly and the issue is solved! Thank you for you help.

**Comment by talgalili** [comment]
Thanks for looking into this @Alanocallaghan !
